// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_CompanyManage.Data;

#nullable disable

namespace Project_CompanyManage.Migrations
{
    [DbContext(typeof(FileTreeContext))]
    [Migration("20250829014748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Project_CompanyManage.Data.FileTree", b =>
                {
                    b.Property<string>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderCreateDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderCreateUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderDepth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperFolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId");

                    b.ToTable("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
